update source code for check all warning

diff --git a/DASAN/bash_script/test/project_test/mshell b/DASAN/bash_script/test/project_test/mshell
--- a/DASAN/bash_script/test/project_test/mshell
+++ b/DASAN/bash_script/test/project_test/mshell
@@ -31,22 +31,31 @@ func_handler()
 		fi
 		local header=$(echo $line|awk '{print $2}'|cut -d':' -f1)
         case $sum in
-                ${data[0]})
+				${data[0]})
                         # unknown type name error
-                        er=$(echo $line|awk '{for ( i = 1; i <= NF; i++ )
-                        if ( $i=="name" ) print $(i+1)}')
-                        er=""
-                        er1=$(echo $line|awk '{for ( i = 1; i <= NF; i++ )
-                        if ( $i=="function" ) print $(i+1)}')
-                        ps=$(echo $line|awk '{print $0}'|cut -d':' -f2)
-                        fn=$(if [ -z $er1 ]
-                        then
-                                tuananh=10;
-                        else
-                                echo "function"
-                        fi)
-						echo "$header ${error_type[0]} $er $er1 $ps"
-                        ;;
+						header=$(echo $line|awk '{print $2}'|cut -d':' -f1)
+            			            ps=$(echo $line|awk '{print $0}'|cut -d':' -f2)
+						er=$(echo $line|awk '{for ( i = 1; i <= NF; i++ )
+            			            if ( $i=="name" ) print $(i+1)}')
+            			            er1=$(echo $line|awk '{for ( i = 1; i <= NF; i++ )
+            			            if ( $i=="function" ) print $(i+1)}')
+						#variable detect missing pthread flags
+            			            er2=$(echo $line|awk '{for ( i = 1; i <= NF; i++ )
+            			            if ( $i=="reference" ) print $(i+2)}')
+						if [ -z $er2 ]; then 
+							temp=10; 
+						else 
+							error_type[0]="reference";
+							ps="0"
+						fi
+						out_data=$(echo "$header ${error_type[0]} $er $er1 $er2 $ps"|wc -w)
+						if [ $out_data -gt 4 ]; then
+							echo "None None None None"
+							return 127
+						else
+							echo "$header ${error_type[0]} $er $er1 $er2 $ps"
+						fi
+            			            ;;
                 ${data[1]})
                         # expected character ";"
                         er=$(echo $line|awk '{for ( i = 1; i <= NF; i++ )
@@ -65,10 +74,6 @@ func_handler()
                         ;;
              esac
 }
-
-
-
-
 
 function test_get_lib_flag()
 {
@@ -89,7 +94,7 @@ function test_add_lib_flag()
 		echo "error at add_lib_flag for $1"
 		return 127
 	fi
-	
+	return 0
 }
 
 function test_add_semicolon()
@@ -104,12 +109,10 @@ function test_add_semicolon()
 
 function check_un_ex_und()
 {
-#awk '/error:/ {print NR,$0}' $output_file_check > "$output_file_check_after_find"
-
-#	local ret=$(func_handler unknown expected undeclared )
 	awk '/warning:/ {print NR,$0}' $output_file_check > "$output_file_check_after_find"
 
 	local ret=$(func_handler implicit kkka kkkk)
+	local ret2
 
 	IFS=' ' read -r -a array <<< "$ret"
 	
@@ -118,13 +121,22 @@ function check_un_ex_und()
 	local tmp_var=$(echo ${array[2]:1:$length})
 
 	test_add_lib_flag "${array[0]}" $tmp_var
+	ret2=$?
+#echo "ret from test_add_lib_flag is $?"
+
+	if [[ $ret2 != 0 ]]; then 
+#echo "failed in check un ex und"
+		return 127	
+	fi
 
 	rm  -f $output_file_check $output_file_check_after_find 
 
 }
 function rebuild()
-{
-	make FLAGS="$FLAGS $ret_option" FILE_IN=$OUTPUT_FILE &> "$output_file_check"
+{   
+	local input_file=$1
+	echo "$oFLAG"
+	make FLAGS="$oFLAGS" FILE_IN="$input_file" &> "$output_file_check"
 }
 
 prepare_header $db_file
@@ -133,10 +145,29 @@ if [[ $? != 0 ]]; then
 else 
 	echo "complete get db.txt"
 fi
-#make >& ${output_file_check}
 
-rebuild
-check_un_ex_und
+function mloop()
+{
+	local ret
+	rebuild "main.c"
 
+	while : ; do 
+	check_un_ex_und
+	ret=$?
+	echo "ret after check un_ex_und is $?"
+	if [[ $ret != 0 ]]; then 
+		echo "skip this warning, this warning have supported yet"		
+		break
+	fi
 
+	head -n 6 output.c
+	cp output.c output2.c
+	rebuild "output2.c"
+
+	done ;	
+
+	make clean_trash
+
+}
+mloop
 
